substitutions:
  comment: "...any comment here, like the device hostname..."
  platform: ESP8266
  board: esp01_1m
  devicename: my_bpdim_1
  propername: "My BPDIM 1"
  min_brightness: '10'
  max_brightness: '1000'

esphome:
  name: $devicename
  platform: $platform
  board: $board
  comment: "${comment}"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on

  ap:
    ssid: AP_${devicename}

captive_portal:

ota:
  password: !secret ota_pass

api:
  encryption:
    key: !secret encryption_key

# disable serial logging by setting baud_rate to 0 because baud_rate/serial connection is used by tuyamcu
logger:
  baud_rate: 0

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:

light:
  - platform: "tuya"
    name: "${propername}"
    dimmer_datapoint: 2
    switch_datapoint: 1
    min_value: $min_brightness
    max_value: $max_brightness