api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Bar-Pendant-Left"
    password: !secret hotspot_password

substitutions:
  name: bar-pendant-left
  device: bar_pendant_left
  friendly_name: Bar Pendant Left

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: ${device}
          brightness: 100%
          color_brightness: 0%
          color_temperature: 2200K

bk72xx:
  board: wb3l

logger:

captive_portal:

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    device:
      name: Device Info
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

button:
  - platform: restart
    name: Restart

sensor:
  - platform: uptime
    device_class: duration
    name: Uptime

sm2135:
  data_pin: GPIO6
  clock_pin: GPIO7
  separate_modes: false
  cw_current: 30mA
  rgb_current: 20mA

output:
  - platform: sm2135
    id: output_blue
    channel: 0
  - platform: sm2135
    id: output_green
    channel: 1
  - platform: sm2135
    id: output_red
    channel: 2
  - platform: sm2135
    id: warm_white
    channel: 3
  - platform: sm2135
    id: cold_white
    channel: 4

light:
  - platform: rgbww
    name: Light
    id: ${device}
    color_interlock: true
    red: output_red
    green: output_green
    blue: output_blue
    warm_white: warm_white
    cold_white: cold_white
    cold_white_color_temperature: 6200K
    warm_white_color_temperature: 2000K