substitutions:
  device_name: My Lumary Disk Light

esphome:
  name: ${device_name}

libretiny:
  board: generic-bk7231n-qfn32-tuya
  framework:
    version: latest

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

api:


bp5758d:
  data_pin: P7
  clock_pin: P6

output:
  - platform: bp5758d
    id: output_red
    channel: 3
  - platform: bp5758d
    id: output_green
    channel: 2
  - platform: bp5758d
    id: output_blue
    channel: 1
  - platform: bp5758d
    id: output_white
    channel: 5
  - platform: bp5758d
    id: output_warmwhite
    channel: 4

light:
  - platform: rgbww
    name: ${device_name}
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_white
    warm_white: output_warmwhite
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    color_interlock: true