substitutions:https://docs.libretiny.eu/docs/platform/beken-72xx/#wiring
  project_name: outdoor-Plug
  friendly_name: "Outdoor Plug"

esphome:
  name: ${project_name}
  friendly_name: ${friendly_name}

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Note: UART config is optional
uart:
  rx_pin: P10 #RX1
  tx_pin: P11 #TX1
  baud_rate: 115200

output:
  - platform: gpio
    pin: P8
    id: 'relay'

binary_sensor:
  - platform: gpio
    id: button_physical
    internal: false  # optional if you'd like the button state in HA, change to true
    pin:
      number: P6
      inverted: true
      mode: INPUT_PULLUP

light:
  - platform: status_led
    id: led_status
    pin:
      number: P7
      inverted: true
# - platform: binary
#   id: lights
#   name: ${friendly_name} lights
#   output: rly_sw
#   on_turn_on:
#     - light.turn_on: led_status
#   on_turn_off:
#     - light.turn_off: led_status

# Note: If you only have lights plugged into the SmartPlug, you could use
# and light component instead of a switch. The automations included below
# mimic the operation of the device with factory firmware.

switch:
  - platform: output
    id: rly_sw
    name: ${friendly_name}
    output: relay
    on_turn_on:
      - light.turn_on: led_status
    on_turn_off:
      - light.turn_off: led_status

logger:
api:
  encryption:
    key: ""
ota:
  password: ""
wifi:
  networks:
  ap:
    password: !secret captive_portal_ap_password
captive_portal: