esphome:
  name: mLinkRelayExample
  friendly_name: mLink Relay Example
  
  includes:
    - mLinkRelay.h
  
  libraries:
    - "Wire"
    - "mlink"

switch:
- platform: custom
  lambda: |-
    auto mLinkRelay0 = new mLinkRelay(0);
    App.register_component(mLinkRelay0);

    auto mLinkRelay1 = new mLinkRelay(1);
    App.register_component(mLinkRelay1);

    auto mLinkRelay2 = new mLinkRelay(2);
    App.register_component(mLinkRelay2);

    auto mLinkRelay3 = new mLinkRelay(3);
    App.register_component(mLinkRelay3);

    return {mLinkRelay0, mLinkRelay1, mLinkRelay2, mLinkRelay3};

  switches:
    - name: "mLink Relay 0"
      id: mLinkRelay0
    - name: "mLink Relay 1"
      id: mLinkRelay1
    - name: "mLink Relay 2"
      id: mLinkRelay2
    - name: "mLink Relay 3"
      id: mLinkRelay3