# Basic Config

substitutions:
  device_name: led_strip
  device_description: CCT LED Strip.
  friendly_name: CCT LED strip

esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap: #since we listed an SSID above, this AP mode will only enable if no WiFi connection could be made
    ssid: ${friendly_name}_AP
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:
  baudrate: 0 #Disable UART logging

# Enable Home Assistant API
api:

ota:

# Enable web server
web_server:
  port: 80

# Device Specific Config

light:
  - platform: cwww
    name: "CCT Lights"
    cold_white: cold_white_channel
    warm_white: warm_white_channel
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K

output:
  - platform: esp8266_pwm
    id: warm_white_channel
    pin: GPIO13
  - platform: esp8266_pwm
    id: cold_white_channel
    pin: GPIO5