substitutions:
  device_name: holman_led_spotlight
  friendly_name: "Holman LED Spotlight"

#################################

esphome:
  name: ${devicename}

bk72xx:
  board: generic-bk7231n-qfn32-tuya

#################################

## ----------------- ##
##      Buttons      ##
## ----------------- ##
binary_sensor:
  - platform: gpio
    pin:
      number: P20
      inverted: true
      mode:
        input: true
        pullup: true
    name: "LED_button"

## ------------ ##
##    Lights    ##
## ------------ ##
light:
  - platform: beken_spi_led_strip
    rgb_order: RGB
    pin: P16
    num_leds: 5
    id: rgb_led
    chipset: ws2812
    is_wrgb: true
    name:  "Light"