esphome:
  name: xs-ssa05
  friendly_name: XS SSA05 Smart Plug

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Remove the following line if you're not using Home Assistant or your switch will restart every now and again
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  # Button (GPIO13)
  - platform: gpio
    name: "XS-SSA05 Button"
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay

  # Device status
  - platform: status
    name: "XS-SSA05 Status"

sensor:
  # WiFi Signal
  - platform: wifi_signal
    name: "XS-SSA05 WiFi Signal"
    update_interval: 60s

  # HLW8012 Power Sensor
  - platform: hlw8012
    sel_pin:
      number: GPIO03
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current:
      name: "XS-SSA05 Current"
      accuracy_decimals: 2
    voltage:
      name: "XS-SSA05 Voltage"
      accuracy_decimals: 2
    power:
      name: "XS-SSA05 Power"
      accuracy_decimals: 2
    energy:
      name: "XS-SSA05 Energy"
      accuracy_decimals: 2
      filters:
        - multiply: 0.001 # Convert Wh to kWh

switch:
  # Relay (GPIO12)
  - platform: gpio
    name: "XS-SSA05 Relay"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - output.turn_on: relay_led
    on_turn_off:
      - output.turn_off: relay_led

time:
  - platform: sntp
    id: my_time

status_led:
  # Status LED (Blue LED on GPIO15)
  pin:
    number: GPIO15
    inverted: False

output:
  # Red LED for Relay Status (GPIO0)
  - platform: gpio
    pin:
      number: GPIO0
      inverted: True
    id: relay_led