substitutions:
  device_name: deta_double_powerpoint
  friendly_name: "Deta Double Powerpoint"

#################################

esphome:
  name: ${devicename}

bk72xx:
  board: generic-bk7231t-qfn32-tuya

packages:
  device_base: !include { file: common/device_base.yaml, vars: { friendlyname : 'Deta Double Power Point'} }

#################################

## ---------------- ##
##    Status LED    ##
## ---------------- ##
status_led:
  pin:
    number: P8
    inverted: true

## ----------------- ##
##      Buttons      ##
## ----------------- ##
binary_sensor:
  # Left Button
  - platform: gpio
    pin:
      number: P14
      # number: P7
      mode: INPUT
      inverted: True
    id: left_button
    on_press:
      then:
        - switch.toggle: switch_left
    internal: True

  # Right Button
  - platform: gpio
    pin:
      number: P24
      mode: INPUT
      inverted: True
    id: right_button
    on_press:
      then:
        - switch.toggle: switch_right
    internal: True

switch:
  ## ---------------- ##
  ##      Relays      ##
  ## ---------------- ##
  # Left Switch
  - platform: gpio
    pin: P6
    id: relay_left

  # Right Switch
  - platform: gpio
    pin: P26
    id: relay_right

  ## ---------------- ##
  ##     Switches     ##
  ## ---------------- ##
  # Left Switch
  # Left Switch (Templated)
  - platform: template
    id: switch_left
    name: ${friendlyname_left}
    icon: ${deviceicon_left}
    lambda: |-
      if (id(relay_left).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: relay_left
    turn_off_action:
      - switch.turn_off: relay_left

  # Right Switch (Templated)
  - platform: template
    id: switch_right
    name: ${friendlyname_right}
    icon: ${deviceicon_right}
    lambda: |-
      if (id(relay_right).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: relay_right
    turn_off_action:
      - switch.turn_off: relay_right