esphome:
  name: shelly-pro-1

esp32:
  board: esp32dev
  framework:
    type: arduino


logger:

api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Shelly-Pro-1"
    password: "BzwFc7HsRihG"

captive_portal:

light:
  - platform: status_led
    name: "Switch state"
    pin:
      sn74hc595: sn74hc595_hub
      number: 1
      inverted: true

#ethernet:
#  type: LAN8720
#  mdc_pin: GPIO23
#  mdio_pin: GPIO18
#  clk_mode: GPIO17_OUT


button:
  - platform: restart
    id: restart_1

binary_sensor:

  - platform: status
    id: status_1
    on_press:
      then:
        switch.turn_on: rgb_b
    on_release:
      then:
        switch.turn_off: rgb_b

  - platform: gpio
    id: reset_button
    pin:
      number: 35
      inverted: true
    on_click:
      min_length: 400ms
      max_length: 800ms
      then:
        button.press: restart_1
    on_double_click:
      then:
        switch.toggle: light1

  - platform: gpio
    id: input1
    pin:
      number: 38
    on_press:
      then:
        switch.toggle: light1

  - platform: gpio
    id: input2
    name: "Shelly Pro Button 2"
    pin:
      number: 39

sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: GPIO13
    clock_pin: GPIO14
    latch_pin: GPIO4
    sr_count: 1

switch:
  - platform: gpio
    name: "Shelly Pro Relay"
    id: light1
    pin:
      sn74hc595: sn74hc595_hub
      number: 0
      inverted: false

  - platform: gpio
    id: out2
    pin:
      sn74hc595: sn74hc595_hub
      number: 1
      inverted: false

  - platform: gpio
    id: rgb_b
    pin:
      sn74hc595: sn74hc595_hub
      number: 2
      inverted: false

  - platform: gpio
    id: rgb_g
    pin:
      sn74hc595: sn74hc595_hub
      number: 3
      inverted: false

  - platform: gpio
    id: rgb_r
    pin:
      sn74hc595: sn74hc595_hub
      number: 4
      inverted: false