esphome:
  name: esp12frelayx1

esp8266:
  board: esp12e

# Use the red LED in the device as a status LED, which will blink if there are warnings (slow) or errors (fast)
status_led:
  pin:
    number: GPIO16
    inverted: True

# relay output, exposed as switch in Home Assistant
switch:
  - platform: gpio
    pin: GPIO5
    name: Relay
    id: relay