esphome:
  name: globe-outdoor-plug-1
  friendly_name: "Globe Outdoor Plug 1"

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:
  level: verbose

web_server:
  version: 3

captive_portal:

mdns:

api:

ota:
  - platform: esphome

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P6
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1

switch:
  - platform: gpio
    id: switch_1
    name: Relay 1
    pin: P8
    on_turn_on:
      - light.turn_on: light_status
    on_turn_off:
      - light.turn_off: light_status

light:
  - platform: status_led
    id: light_status
    pin:
      number: P7
      inverted: true

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version