esp8266:
  board: esp_wroom_02

uart:
  rx_pin: GPIO13 # U1RX
  tx_pin: GPIO15 # U1TX
  baud_rate: 9600

tuya:
  on_datapoint_update:
    - sensor_datapoint: 11
      datapoint_type: bitmask
      then:
        - lambda: |-
            ESP_LOGD("main", "on_datapoint_update %s", format_hex_pretty(x).c_str());
            // only seen in the wild is decimal value 8, for Water Tank Full
            id(water_tank_full).publish_state((x >> 3) & 1);

binary_sensor:
  - platform: template
    id: water_tank_full
    name: "Water tank"
    device_class: problem
    icon: "mdi:water-alert"
  - platform: tuya
    name: "Unknown 101"
    sensor_datapoint: 101
    internal: true
  - platform: tuya
    name: "Unknown 105"
    sensor_datapoint: 105
    internal: true

switch:
  - platform: tuya
    name: "Power"
    switch_datapoint: 1
  - platform: tuya
    name: "Air clean"
    icon: "mdi:leaf"
    switch_datapoint: 5
  - platform: tuya
    name: "Child lock"
    icon: "mdi:lock"
    switch_datapoint: 7
  - platform: tuya
    name: "Sleep"
    icon: "mdi:sleep"
    switch_datapoint: 102

number:
  - platform: tuya
    name: "Target humidity"
    number_datapoint: 4
    unit_of_measurement: "%"
    device_class: "humidity"
    min_value: 30
    max_value: 80
    step: 5

sensor:
  - platform: tuya
    name: "Temperature"
    sensor_datapoint: 103
    unit_of_measurement: "°C"
    device_class: "temperature"
    accuracy_decimals: 0
  - platform: tuya
    name: "Humidity"
    sensor_datapoint: 104
    unit_of_measurement: "%"
    device_class: "humidity"
    accuracy_decimals: 0

select:
  - platform: tuya
    name: "Mode"
    icon: "mdi:cog"
    enum_datapoint: 2
    options:
      0: Regular
      1: Automatic
      2: Strong
      3: Clothes drying
  - platform: tuya
    name: "Fan speed"
    icon: "mdi:fan"
    enum_datapoint: 6
    options:
      0: Low
      1: High
#  - platform: tuya
#    name: "Unknown"
#    enum_datapoint: 12