esphome:
  name: h802light

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  hardware_uart: UART1
api:
ota:

output:
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_w1
light:
  - platform: rgbw
    name: "H802 Light"
    red: pwm_r
    green: pwm_g
    blue: pwm_b
    white: pwm_w1