# Everything from the basic configuration should go here
# ...

sensor:
  # The HLW8012 platform entry (required)
  # All other sensor platform entries should go here
  # ...

  # Total Daily Energy Sensor
  # More information available at https://esphome.io/components/sensor/total_daily_energy
  - platform: total_daily_energy
    name: 'Total Daily Energy'
    power_id: wattage
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001

# Time Component
# This will reset the "Total Daily Energy Sensor" to 0 at midnight, synced with Home Assistant's clock.
time: # More information available at https://esphome.io/components/time
  - platform: homeassistant
    id: homeassistant_time

# Everything from the basic configuration should go here.
# ...

sensor:
  # All other sensor platform entries should go here.
  # ...

  # Debug component
  # More information at https://esphome.io/components/debug
  - platform: debug
    free:
      name: "Heap Free"
    fragmentation:
      name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"

# Enable this to update the debugging sensor.
debug:
  update_interval: 5s