# Basic Config
esphome:
  name: "arlec_GLD112HA"

esp8266:
  board: esp01_1m
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: "password"

output:
  - platform: esp8266_pwm
    id: dimmer
    pin: GPIO5
  - platform: esp8266_pwm
    id: color_temp
    pin: GPIO13
    inverted: true

light:
- platform: color_temperature
  name: "Arlec GLD112HA"
  color_temperature: color_temp
  brightness: dimmer
  cold_white_color_temperature: 5700 K
  warm_white_color_temperature: 3000 K