substitutions:
  name: localbytes-bulb-<NAME>
  friendly_name: Localbytes Bulb <NAME>

packages:
  jamesswift.localbytes-bulb-9w-rgbct: github://JamesSwift/localbytes-bulb-9w-rgbct/localbytes-bulb-9w-rgbct.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password