substitutions:
  device_name: masterlight
  friendly_name: "Master Bedroom Overhead"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-c3-devkitm-1

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  networks:
  - ssid: !secret guest_ssid
    password: !secret guest_password
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome ${device_name}"
    password: !secret wifi_password_backup

# Enable NTP
time:
  - platform: sntp
    id: my_time

# General Config
text_sensor:
  - platform: version
    name: "${device_name} Version"
  - platform: wifi_info
    ip_address:
      name: "${device_name} IP Address"
    ssid:
      name: "${device_name} SSID"
    bssid:
      name: "${device_name} BSSID"

sensor:
  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 60s
    filters:
      - delta: 0.01
      - throttle: 300s
  - platform: uptime
    name: "${device_name} Uptime"
    filters:
      - throttle: 300s

light:
  # RGB Mood Light
  - platform: rgb
    name: "RGB Light"
    red: output_pwm1
    green: output_pwm2
    blue: output_pwm3
    restore_mode: RESTORE_DEFAULT_OFF
  # Temperature controlled light
  - platform: cwww
    name: "Room Light"
    cold_white: output_pwm4
    warm_white: output_pwm5
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: True
    restore_mode: RESTORE_DEFAULT_ON

output:
  # Red PWM
  - platform: ledc
    id: output_pwm1
    pin: GPIO10
    zero_means_zero: True
  # Green PWM
  - platform: ledc
    id: output_pwm2
    pin: GPIO3
    max_power: 70%
    zero_means_zero: True
  # Blue PWM
  - platform: ledc
    id: output_pwm3
    pin: GPIO4
    max_power: 75%
    zero_means_zero: True
  # Cool PWM
  - platform: ledc
    id: output_pwm4
    pin: GPIO18
    zero_means_zero: True
  # Warm PWM
  - platform: ledc
    id: output_pwm5
    pin: GPIO5
    zero_means_zero: True