esphome:
  name: ecoplug
  friendly_name: EcoPlug

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret

ota:
  platform: esphome
  password: !secret

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$proper_devicename Hotspot"
    password: !secret ap_password
sensor:
  - platform: wifi_signal
    name: "Wifi Signal"
    update_interval: 120s
    entity_category: "Diagnostic"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
    id: button
    on_press:
     - switch.toggle: relay1

  - platform: status
    name: Eco Plug
    entity_category: "Diagnostic"

text_sensor:
  - platform: version
    name: "Firmware Version"
    entity_category: "Diagnostic"

switch:
  - platform: gpio
    name: "Eco Plug 1"
    pin: GPIO15
    id: relay1
    icon: "mdi:power-socket-us"

output:
  - platform: gpio
    id: blue_led
    pin: GPIO02
    inverted: true

interval:
  - interval: 1s
    then:
     if:
       condition:
         wifi.connected:
       then:
         - output.turn_on: blue_led
       else:  #blinks if wi-fi isn't connected
         - output.turn_on: blue_led
         - delay: 500ms
         - output.turn_off: blue_led

captive_portal:
# Example configuration entry
web_server:
  port: 80
  version: 1