esphome:
  name: esp32-relay-x2

esp32:
  board: esp32dev

# LED exposed as binary light
output:
  - platform: gpio
    pin: GPIO23
    id: output_led

light:
  - platform: binary
    id: light_led
    name: LED
    output: output_led

# Relays exposed as switches
switch:
  - platform: gpio
    pin: GPIO16
    id: relay_1
    name: Relay 1

  - platform: gpio
    pin: GPIO17
    id: relay_2
    name: Relay 2