esphome:
  name: led-ceiling-light
  friendly_name: "LED Ceiling Light"
  project:
    name: "Oyajia.AS105"
    version: "AS105"
  on_boot:
    priority: 600
    then:
    - light.turn_on:
        id: white_light
        brightness: 70%
        color_temperature: 2800 K

bk72xx:
  board: generic-bk7231n-qfn32-tuya

api:
  encryption:
    key: !secret api_encryption_key

ota:
  id: my_ota
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  baud_rate: 2000000  # The original firmware uses the same baud rate for log outputs
  hardware_uart: UART1

external_components:
  - source: github://pr#6515
    components: [beken_spi_led_strip]
    refresh: always

light:
  - platform: cwww
    id: white_light
    name: "White Light"
    cold_white: output_cw
    warm_white: output_ww
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2800 K
    constant_brightness: true

  - platform: beken_spi_led_strip
    id: color_light
    name: "Color Light"
    pin: P16
    chipset: WS2812
    num_leds: 60
    rgb_order: GRB

output:
  - platform: libretiny_pwm
    id: output_cw
    pin: PWM1
    # min_power: 14%
    # zero_means_zero: True
  - platform: libretiny_pwm
    id: output_ww
    pin: PWM2
    # min_power: 14%
    # zero_means_zero: True

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"