esphome:
  name: wemos
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "ssid"
  password: "wifi_password"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: "ota_password"

binary_sensor:
  - platform: gpio
    pin:
      number: D7
      mode: INPUT_PULLUP
      inverted: true
    name: "Volume Switch Button"

sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_b:
      number: D6
      mode: INPUT
    pin_a:
      number: D5
      mode: INPUT
    max_value: 100
    min_value: 0
    resolution: 4

- id: Adjust Volume on Rotary Encoder Move
  alias: Rotary Volume Change
  trigger:
    - platform: state
      entity_id: sensor.rotary_encoder
  action:
    - service: media_player.volume_set
      entity_id: media_player.kitchen
      data_template:
        volume_level: "{{ states.sensor.rotary_encoder.state | float / 100 }}"