# Basic Config
---
substitutions:
  device_name:   "energy-meter"
  friendly_name: "Energy Meter"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  on_connect:
    - output.turn_on:  tuya_led_wifi
  on_disconnect:
    - output.turn_off: tuya_led_wifi

logger:
  baud_rate: 0

api:

ota:
  - platform: esphome

uart:
  rx_pin: GPIO03
  tx_pin: GPIO01
  baud_rate: 9600

tuya:
  on_datapoint_update:
    - sensor_datapoint: 6
      datapoint_type: raw
      then:
        - lambda: |-
            ESP_LOGD("main", "on_datapoint_update %s", format_hex_pretty(x).c_str());
            id(voltage).publish_state((x[13] << 8 | x[14]) * 0.1);
            id(current).publish_state((x[11] << 8 | x[12]) * 0.001);

#            id(power_active).publish_state((x[02] << 8 | x[03]) * 0.001);   # Power Active   in kW   - DP103
#            id(power_reactive).publish_state((x[06] << 8 | x[07]) * 0.001); # Power Reactive in kVAr - DP110

output:
  - platform: gpio
    pin: GPIO14
    id: tuya_led_wifi
    inverted: True

switch:
  - platform: "tuya"
    id: sw_relay
    name: "Switch"
    switch_datapoint: 16

  - platform: "tuya"
    name: "Restore on startup"
    switch_datapoint: 11
    inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      inverted: True
    name: "SET long press"

sensor:
  - platform: template
    id: voltage
    name: "Voltage"
    device_class: voltage
    unit_of_measurement: V
    state_class: measurement
    accuracy_decimals: 1

  - platform: template
    id: current
    name: "Current"
    device_class: current
    unit_of_measurement: A
    state_class: measurement
    accuracy_decimals: 3

  - platform: "tuya"
    name: "Frequency"
    sensor_datapoint: 105
    device_class: frequency
    unit_of_measurement: Hz
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: "tuya"
    id: power_active
    name: "Power Active"
    sensor_datapoint: 103
    device_class: power
    unit_of_measurement: kW
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: "tuya"
    id: power_reactive
    name: "Power Reactive"
    sensor_datapoint: 110
    device_class: power
    unit_of_measurement: kVAr
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: "tuya"
    name: "Power Factor"
    sensor_datapoint: 111
    device_class: power_factor
    state_class: measurement
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: "tuya"
    name: "Energy"
    sensor_datapoint: 101
    device_class: energy
    unit_of_measurement: kWh
    state_class: total_increasing
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: "tuya"
    name: "Energy from Grid"
    sensor_datapoint: 1
    device_class: energy
    unit_of_measurement: kWh
    state_class: total_increasing
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: "tuya"
    name: "Energy to Grid"
    sensor_datapoint: 102
    device_class: energy
    unit_of_measurement: kWh
    state_class: total_increasing
    accuracy_decimals: 3
    filters:
      - multiply: 0.001