remote_receiver:
  dump:
    - nec
  pin:
    number: P7
    inverted: true
    mode: INPUT_PULLUP

binary_sensor:
  - platform: remote_receiver
    id: "off"
    nec:
      address: 0xFBE2
      command: 0xDA25
    on_press:
      then:
        - light.turn_off:
            id: light_monochromatic
  - platform: remote_receiver
    id: "on"
    nec:
      address: 0xFBE2
      command: 0xD926
    on_press:
      then:
        - light.turn_on:
            id: light_monochromatic
  - platform: remote_receiver
    id: "lower"
    nec:
      address: 0xFBE2
      command: 0x916E
    on_press:
      then:
        - light.dim_relative:
            id: light_monochromatic
            relative_brightness: -5%
            transition_length: 0s
  - platform: remote_receiver
    id: "higher"
    nec:
      address: 0xFBE2
      command: 0xF00F
    on_press:
      then:
        - light.dim_relative:
            id: light_monochromatic
            relative_brightness: 5%
            transition_length: 0s