# Basic Config
esphome:
  name: kicony-kc868-a2
  friendly_name: KinCony KC868-A2

esp32:
  board: esp32dev
  framework:
    type: arduino

# your OTA/API/Wifi/logger boilerplate here

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

switch:
  - platform: gpio
    name: "a2-light1"
    pin: 15
    inverted: False
  - platform: gpio
    name: "a2-light2"
    pin: 2
    inverted: False

binary_sensor:
  - platform: gpio
    name: "a2-input1"
    pin:
      number: 36
      inverted: true
  - platform: gpio
    name: "a2-input2"
    pin:
      number: 39
      inverted: true