substitutions:
  friendly_name: Mi Bulb 01
  device_name: mibulb-01

# Basic Config
esphome:
  name: ${device_name}
  comment: ${friendly_name}

esp8266:
  board: modwifi

# WiFi connection
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: ${device_name}.local
  ap:
    ssid: ${device_name}_fallback_ap
    password: !secret ap_password

# Enable captive portal
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Enable Web server
web_server:
  port: 80

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  - platform: version
    name: ${friendly_name} ESPHome Version
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address

sensor:
  # Uptime sensor
  - platform: uptime
    name: ${friendly_name} Uptime
  # WiFi Signal sensor
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    update_interval: 60s

output:
  - platform: esp8266_pwm
    pin: GPIO5
    id: pwm1
    # frequency: 1000Hz
  - platform: esp8266_pwm
    pin: GPIO13
    id: pwm2
    # frequency: 1000Hz
  - platform: esp8266_pwm
    pin: GPIO12
    id: pwm3
    # frequency: 1000Hz
  - platform: esp8266_pwm
    pin: GPIO14
    id: pwm4
    # frequency: 1000Hz

light:
  - platform: monochromatic
    name: ${friendly_name} Light
    output: pwm1
    id: light01
    # Ensure the light turns on by default if the physical switch is actuated.
    restore_mode: ALWAYS_ON
    default_transition_length: 0.2s