esphome:
  name: gosundsw5
  platform: ESP8266
  board: esp01_1m

substitutions:
  esphome_name: gosundsw5
  friendly_name: Gosund SW6

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

status_led:
  pin:
    number: GPIO16
    inverted: True

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
    id: button
    on_press:
      - switch.toggle: relay

  - platform: gpio
    pin:
      number: GPIO4
      inverted: True
    id: power_button
    name: "Dumb Switch Output"
    internal: True
    on_press:
      - switch.toggle: ${esphome_name}

switch:
  - platform: gpio
    pin: GPIO14
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
    internal: True

  - platform: template
    name: ${friendly_name}
    id: ${esphome_name}
    icon: "mdi:light-switch"
    lambda: |-
      if (id(power_button).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - if:
          condition:
            - binary_sensor.is_off: power_button
          then:
            - switch.toggle: relay
    turn_off_action:
      - if:
          condition:
            - binary_sensor.is_on: power_button
          then:
            - switch.toggle: relay

  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLDOWN_16
    id: dummy_relay
    internal: True