esphome:
  name: ghome_sw5
  friendly_name: Ghome SW5

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Ghome SW5 Fallback Hotspot"
    password: !secret fallback_password

captive_portal:

# Status LED configuration
status_led:
  pin:
    number: P7  # WiFi/Green LED
    inverted: true

# Output configuration for the red LED
output:
  - platform: gpio
    id: red_led
    pin:
      number: P16  # Red LED
      inverted: false

# Light configuration for Home Assistant
light:
  - platform: binary
    output: red_led
    id: led
    name: "Red LED"

# Binary sensor for the button
binary_sensor:
  - platform: gpio
    pin:
      number: P8  # Button
      mode: INPUT_PULLUP
    id: button1
    on_press:
      then:
        - switch.toggle: relay1

# Relay switch configuration
switch:
  - platform: gpio
    pin: P14  # Relay
    id: relay1
    name: "Relay Switch"
    on_turn_on:
      - light.turn_off: led  # Turn off the red LED when relay is on
    on_turn_off:
      - light.turn_on: led  # Turn on the red LED when relay is off