substitutions:
  device_name: detadimmerwitch
  friendly_name: "Dimmer Switch"

#################################

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

# ESP-Based Board
#board: esp01_1m
#esp8266_restore_from_flash: true

bk72xx:
  board: wb3s

# disable logging over UART
logger:
  baud_rate: 0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback"
    password: "12345678"

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

# The web_server & sensor components can be removed without affecting core functionaility.
web_server:
  port: 80

#################################
captive_portal:

# espsetup
#uart:
#  rx_pin: GPIO3
#  tx_pin: GPIO1
#  baud_rate: 9600

uart:
  rx_pin: P10
  tx_pin: P11
  baud_rate: 9600

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${device_name} Uptime

# Register the Tuya MCU connection
tuya:

# light settings
light:
  - platform: "tuya"
    name: "${friendly_name}"
    # dimmers current value
    dimmer_datapoint: 2
    # dimmer on/off
    switch_datapoint: 1
    min_value_datapoint: 3
    min_value: 0
    max_value: 1000

switch:
  - platform: restart
    name: "${friendly_name} REBOOT"