esphome:
  name: shelly-3em

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable HA API
api:
  encryption:
    key: !secret api_key

# Enable OTAs
ota:
  password: !secret api_password

# Sync RTC with HA
time:
  - platform: homeassistant
    timezone: America/Chicago

# Wi-Fi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  power_save_mode: LIGHT

  # Enable fallback hotspot (captive portal) in case Wi-Fi connection fails
  ap:
    ssid: shelly-3em AP
    password: !secret ap_password

captive_portal:

i2c:
  sda: GPIO12
  scl: GPIO14
  frequency: 200kHz

status_led:
  pin:
    number: GPIO2

switch:
  - id: relay
    name: Shelly 3EM Relay
    platform: gpio
    pin:
      number: GPIO15

binary_sensor:
  - id: button
    name: Shelly 3EM Button
    platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true

sensor:
  - id: ade7880_device
    platform: ade7880
    irq0_pin:
      number: GPIO13
    irq1_pin:
      number: GPIO5
    reset_pin:
      number: GPIO16
    frequency: 60Hz
    phase_a:
      name: Phase A
      voltage: Voltage
      current: Current
      active_power
        id: phase_a_active_power
        name: Active Power
      power_factor: Power Factor
      forward_active_energy
        id: phase_a_forward_active_energy
        name: Forward Active Energy
      reverse_active_energy: Reverse Active Energy
      calibration:
        current_gain: 3116628
        voltage_gain: -757178
        power_gain: -1344457
        phase_angle: 188
    phase_b:
      name: Phase B
      voltage: Voltage
      current: Current
      active_power:
        name: Active Power
        id: phase_b_active_power
      power_factor: Power Factor
      forward_active_energy:
        name: Forward Active Energy
        id: phase_b_forward_active_energy
      reverse_active_energy: Reverse Active Energy
      calibration:
        current_gain: 3133655
        voltage_gain: -755235
        power_gain: -1345638
        phase_angle: 188
    phase_c:
      name: Phase C
      voltage: Voltage
      current: Current
      active_power:
        name: Active Power
        id: phase_c_active_power
      power_factor: Power Factor
      forward_active_energy:
        name: Forward Active Energy
        id: phase_c_forward_active_energy
      reverse_active_energy: Reverse Active Energy
      calibration:
        current_gain: 3111158
        voltage_gain: -743813
        power_gain: -1351437
        phase_angle: 180
    neutral:
      name: Neutral
      current: Current
      calibration:
        current_gain: 311123
  - platform: combination
    type: sum
    name: "Sum Active Power"
    id: sum_active_power
    sources:
      - source: phase_a_active_power
      - source: phase_b_active_power
      - source: phase_c_active_power
  - platform: combination
    type: sum
    name: "Sum Forward Active Energy"
    state_class: total_increasing
    sources:
      - source: phase_a_forward_active_energy
      - source: phase_b_forward_active_energy
      - source: phase_c_forward_active_energy
  - platform: total_daily_energy
    name: 'Total Daily Energy'
    power_id: sum_active_power
    unit_of_measurement: 'kWh'
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001