substitutions:
  devicename: govee-bulb

esphome:
  name: $devicename

rtl87xx:
  board: generic-rtl8710bn-2mb-468k
  framework:
    version: latest

# Enable logging
logger:

# Enable Home Assistant API
api:

web_server:
  port: 80

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "govee Fallback Hotspot"
    password: !secret ap_password

# Output pins
output:
- platform: ledc
  id: red_color
  pin: GPIO10
  inverted: False
- platform: ledc
  id: green_color
  pin: GPIO07
  inverted: False
- platform: ledc
  id: blue_color
  pin: GPIO06
  inverted: False
- platform: ledc
  id: cold_white
  pin: GPIO12
  inverted: False
  # max_power: 50%
- platform: ledc
  id: warm_white
  pin: GPIO08
  inverted: False
  # max_power: 50%

light:
  - platform: rgbww
    name: "$devicename 5W"
    id: "light_goveebulb_5W"
    red: red_color
    green: green_color
    blue: blue_color
    cold_white: cold_white
    warm_white: warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    color_interlock: true
    restore_mode: ALWAYS_ON
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker: