substitutions:
  device_name: "alrec-gld322ha"
  friendly_name: "Arlec GLD322HA"

esphome:
  name: ${device_name}

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret ota_password

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

web_server:
  port: 80


sm2135:
  data_pin: GPIO01
  clock_pin: GPIO03
  rgb_current: 25mA
  cw_current: 25mA  

# Individual outputs
output:
  - platform: sm2135
    id: output_blue
    channel: 0
    max_power: 1
  - platform: sm2135
    id: output_green
    channel: 1
    max_power: 1
  - platform: sm2135
    id: output_red
    channel: 2
    max_power: 1
  - platform: sm2135
    id: output_white
    channel: 3
    max_power: 1
  - platform: sm2135
    id: output_warmwhite
    channel: 4
    max_power: 1

light:
  - platform: rgbww
    name: ${friendly_name}
    red: output_red
    green: output_green
    blue: output_blue
    cold_white: output_white
    warm_white: output_warmwhite
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 3000 K
    color_interlock: true