esphome:
  name: energy_meter
  platform: ESP8266
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fallback Hotspot"
    password: "xxxxxxxxxxxx"

captive_portal:

sensor:
  - platform: pulse_meter
    pin: D8
    unit_of_measurement: 'kW'
    name: "Active Power"
    internal_filter: 100ms
    accuracy_decimals: 3
    id: orno_we_520_active_power
    filters:
      - multiply: 0.075  # 800 pulses/kW
    total:
      name: "Active Energy"
      id: orno_we_520_power_active_energy
      unit_of_measurement: "kWh"
      accuracy_decimals: 3
      filters:
        - multiply: 0.00125

  - platform: total_daily_energy
    name: 'Daily Energy'
    power_id: orno_we_520_active_power