substitutions:
  device_name: asp-200
  device_name_u: asp_200
  friendly_name: "ASP-200 Window Fan"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp12e
  restore_from_flash: TRUE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

# Enable Home Assistant API
api:
  # https://esphome.io/components/api
  encryption:
    key: !secret api_encryption_key

ota:
  # https://esphome.io/components/ota
  password: !secret ota_password

# Enable Web server.
web_server:
  port: 80

logger:
  baud_rate: 0

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:

fan:
  - platform: tuya
    name: ${friendly_name}
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 3

switch:
  - platform: tuya
    name: "${friendly_name} Power"
    switch_datapoint: 1
    id: "${device_name_u}_power_switch"

select:
  - platform: tuya
    name: "${friendly_name} Speed"
    id: "${device_name_u}_speed"
    enum_datapoint: 3
    optimistic: true
    options:
      0: Low
      1: Medium
      2: High
  - platform: tuya
    name: "${friendly_name} Mode"
    id: "${device_name_u}_mode"
    enum_datapoint: 2
    optimistic: true
    options:
      0: Intake
      1: Exhaust
      2: Circulate

sensor:
  - platform: "tuya"
    name: "${friendly_name} Temperature"
    id: "${device_name_u}_temp"
    sensor_datapoint: 19
    unit_of_measurement: "°F"