bk72xx:
  board: cbu

switch:
  - platform: gpio
    id: relay1
    name: "Relay 1"
    pin: 7
  - platform: gpio
    id: relay2
    name: "Relay 2"
    pin: 26
  - platform: gpio
    id: relay3
    name: "Relay 3"
    pin: 24

output:
  - platform: libretiny_pwm
    id: led
    pin: 6

light:
  - platform: monochromatic
    name: LED
    output: led

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: 8
      inverted: true
      mode: input_pullup
    name: Side button
    on_click:
      then:
        - switch.toggle: relay1