substitutions:
  devicename: aoycocr_x13
  proper_devicename: Aoycocr X13

esphome:
  name: $devicename

esp8266:
  board: esp01_1m
  arduino_version: espressif8266@2.6.2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:


captive_portal:
logger:
api:
ota:

# https://tasmota.github.io/docs/Components/
# https://templates.blakadder.com/aoycocr_X13.html

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
    id: button
    on_press:
     - switch.toggle: relay1
     - switch.toggle: relay2

  - platform: status
    name: $devicename

switch:
  - platform: gpio
    name: "$devicename 1"
    pin: GPIO15
    id: relay1
    icon: "mdi:floor-lamp"
    #Led2 represents switch 1
    on_turn_on:
      - output.turn_on: led2
    on_turn_off:
      - output.turn_off: led2

  - platform: gpio
    name: "$devicename 2"
    pin: GPIO12
    id: relay2
    icon: "mdi:floor-lamp"

output:
  - platform: gpio
    pin: GPIO0
    id: led2
    inverted: yes

status_led:
  pin:
    number: GPIO2
    inverted: yes