substitutions:
  device_name: "csh-e27ww10w"
  friendly_name: "Connect SmartHome CSH-E27WW10W"

esphome:
  name: ${device_name}
  comment: ${friendly_name}
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

wifi:
  ssid: "ssid"
  password: "password"

  ap:
    ssid: ${device_name}
    password: "password"

captive_portal:

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: "password"

output:
  - platform: esp8266_pwm
    id: cw_color_temp
    pin: GPIO5
  - platform: esp8266_pwm
    id: ww_color_temp
    pin: GPIO13

light:
  - platform: cwww
    name: ${friendly_name}
    cold_white: cw_color_temp
    warm_white: ww_color_temp
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    effects:
      - random:
      - pulse:
      - strobe:
      - flicker: