substitutions:
  device_name: minir4m

esphome:
  name: ${device_name}
  comment: "Sonoff MiniR4M"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32c3.yaml@v2
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

output:
  # Physical relay on GPIO
  - platform: gpio
    pin: GPIO04
    id: relay_1

  # Status LED output
  - platform: gpio
    pin: GPIO19
    id: status_led_output
    inverted: true


light:
  - platform: binary
    id: light_1
    name: ${friendly_name}
    icon: mdi:ceiling-light-multiple-outline
    restore_mode: restore_default_off
    output: relay_1
    on_turn_on:
      - output.turn_on: status_led_output
    on_turn_off:
      - output.turn_off: status_led_output

binary_sensor:
  - platform: gpio
    pin: GPIO09
    id: button
    filters:
      - invert:
      - delayed_off: 50ms
    on_press:
      - light.toggle:
          id: light_1
  - platform: gpio
    name: s1
    pin: GPIO05
    id: s1
    filters:
      - invert:
      - delayed_off: 50ms
    on_state:
      then:
        - light.toggle:
            id: light_1