esp8266:
  board: esp8285
  restore_from_flash: true

remote_receiver:
  pin:
    number: GPIO5
    inverted: true
  dump: all # Dumps received codes to logs.

remote_transmitter:
  pin:
    number: GPIO4
  carrier_duty_percent: 50%

output:
  - platform: gpio
    pin: GPIO12
    id: gpio_12
  - platform: gpio
    pin: GPIO13
    id: gpio_13

switch:
  - name: "Top LED"
    id: led_top
    platform: output
    output: gpio_12
  - name: "Middle LED"
    id: led_middle
    platform: output
    output: gpio_13

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
      inverted: true
    name: Bottom Button
    on_press:
      then:
        - switch.toggle:
            id: led_middle
        - delay: 2s
        - switch.toggle:
            id: led_top