# Change the below substitutions to something you prefer, and update the number for each new device you create
substitutions:
  name: si-smartplug-model-70011
  friendly_name: si-smartplug-model-70011

# BELOW IS COMMON CODE
esphome:
  name: si-smartplug-model-70011
  friendly_name: si-smartplug-model-70011

esp8266:
  board: d1_mini
  early_pin_init: false  # Prevent the physical relay flipping on reboot.

api:
ota:
captive_portal:
web_server:
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  domain: !secret wifi_mydomain
  ap:
    password: !secret ap_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: Relay
    pin: GPIO14
    id: relay
    restore_mode: ALWAYS_ON

status_led:
  pin:
    number: GPIO13
    inverted: True