esphome:
  name: WB5 LED Controller
  friendly_name: WB5 LED Controller

bk72xx:
  board: generic-bk7231n-qfn32-tuya


# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# serial connection to Tuya MCU
uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Enable Home Assistant API
api:
  encryption:
    key: "GET-A-KEY-HERE-https://esphome.io/components/api.html#configuration-variables"

ota:
  password: "CHANGE-THIS-PASSWORD-OR-REMOVE-OTA"

wifi: #if you dont have secrets setup change the values with your wifi name and password
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WB5 LED Controller Fallback Hotspot"
    password: "CHANGE-THIS-PASSWORD-OR-DISABLE-AP-FALLBACK"

# Enable Web server
web_server:
  port: 80

captive_portal:

light:
  - platform: "tuya" # dont forget to set the correct mode whit the button on the controller
    name: "WB5 LED Controller"
    color_interlock: true # infinite loop isue when false (false is default)
    gamma_correct: 1 # has built in gamma correct wil cause issuses when changed
    default_transition_length: 0s # has built in transitions
    switch_datapoint: 20

    # for brightness
    dimmer_datapoint: 22
    min_value: 0
    max_value: 1000 # Max value is 1000 (default is 255)

    # for Correlated Color Temperature(CCT) or white channels
    #color_temperature_datapoint: 23
    #color_temperature_invert: true #set to true if connected as stated on the controller
    #color_temperature_max_value: 1000 # Max value is 1000 (default is 255)
    #cold_white_color_temperature: 6000 K # Change depending on LED strip
    #warm_white_color_temperature: 2700 K # Change depending on LED strip

    # for RGB channels
    #color_datapoint: 24
    #color_type: hsv

esphome:
  name: WB5 LED Controller
  friendly_name: WB5 LED Controller

bk72xx:
  board: generic-bk7231n-qfn32-tuya


# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# serial connection to Tuya MCU
uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Enable Home Assistant API
api:
  encryption:
    key: "GET-A-KEY-HERE-https://esphome.io/components/api.html#configuration-variables"

ota:
  password: "CHANGE-THIS-PASSWORD-OR-REMOVE-OTA"

wifi: #if you dont have secrets setup change the values with your wifi name and password
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WB5 LED Controller Fallback Hotspot"
    password: "CHANGE-THIS-PASSWORD-OR-DISABLE-AP-FALLBACK"

# Enable Web server
web_server:
  port: 80

captive_portal:

light:
  - platform: "tuya" # dont forget to set the correct mode whit the button on the controller
    name: "WB5 LED Controller"
    color_interlock: true # infinite loop isue when false (false is default)
    gamma_correct: 1 # has built in gamma correct wil cause issuses when changed
    default_transition_length: 0s # has built in transitions
    switch_datapoint: 20

    # for brightness
    dimmer_datapoint: 22
    min_value: 0
    max_value: 1000 # Max value is 1000 (default is 255)

    # for Correlated Color Temperature(CCT) or white channels
    color_temperature_datapoint: 23
    color_temperature_invert: true #set to true if connected as stated on the controller
    color_temperature_max_value: 1000 # Max value is 1000 (default is 255)
    cold_white_color_temperature: 6000 K # Change depending on LED strip
    warm_white_color_temperature: 2700 K # Change depending on LED strip

    # for RGB channels
    #color_datapoint: 24
    #color_type: hsv

esphome:
  name: WB5 LED Controller
  friendly_name: WB5 LED Controller

bk72xx:
  board: generic-bk7231n-qfn32-tuya


# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# serial connection to Tuya MCU
uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Enable Home Assistant API
api:
  encryption:
    key: "GET-A-KEY-HERE-https://esphome.io/components/api.html#configuration-variables"

ota:
  password: "CHANGE-THIS-PASSWORD-OR-REMOVE-OTA"

wifi: #if you dont have secrets setup change the values with your wifi name and password
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WB5 LED Controller Fallback Hotspot"
    password: "CHANGE-THIS-PASSWORD-OR-DISABLE-AP-FALLBACK"

# Enable Web server
web_server:
  port: 80

captive_portal:

light:
  - platform: "tuya" # dont forget to set the correct mode whit the button on the controller
    name: "WB5 LED Controller"
    color_interlock: true # infinite loop isue when false (false is default)
    gamma_correct: 1 # has built in gamma correct wil cause issuses when changed
    default_transition_length: 0s # has built in transitions
    switch_datapoint: 20

    # for brightness
    #dimmer_datapoint: 22
    #min_value: 0
    #max_value: 1000 # Max value is 1000 (default is 255)

    # for Correlated Color Temperature(CCT) or white channels
    #color_temperature_datapoint: 23
    #color_temperature_invert: true #set to true if connected as stated on the controller
    #color_temperature_max_value: 1000 # Max value is 1000 (default is 255)
    #cold_white_color_temperature: 6000 K # Change depending on LED strip
    #warm_white_color_temperature: 2700 K # Change depending on LED strip

    # for RGB channels
    color_datapoint: 24
    color_type: hsv

esphome:
  name: WB5 LED Controller
  friendly_name: WB5 LED Controller

bk72xx:
  board: generic-bk7231n-qfn32-tuya


# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# serial connection to Tuya MCU
uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Enable Home Assistant API
api:
  encryption:
    key: "GET-A-KEY-HERE-https://esphome.io/components/api.html#configuration-variables"

ota:
  password: "CHANGE-THIS-PASSWORD-OR-REMOVE-OTA"

wifi: #if you dont have secrets setup change the values with your wifi name and password
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WB5 LED Controller Fallback Hotspot"
    password: "CHANGE-THIS-PASSWORD-OR-DISABLE-AP-FALLBACK"

# Enable Web server
web_server:
  port: 80

captive_portal:

light:
  - platform: "tuya" # dont forget to set the correct mode whit the button on the controller
    name: "WB5 LED Controller"
    color_interlock: true # infinite loop isue when false (false is default)
    gamma_correct: 1 # has built in gamma correct wil cause issuses when changed
    default_transition_length: 0s # has built in transitions
    switch_datapoint: 20

    # for brightness
    dimmer_datapoint: 22
    min_value: 0
    max_value: 1000 # Max value is 1000 (default is 255)

    # for Correlated Color Temperature(CCT) or white channels
    #color_temperature_datapoint: 23
    #color_temperature_invert: true #set to true if connected as stated on the controller
    #color_temperature_max_value: 1000 # Max value is 1000 (default is 255)
    #cold_white_color_temperature: 6000 K # Change depending on LED strip
    #warm_white_color_temperature: 2700 K # Change depending on LED strip

    # for RGB channels
    color_datapoint: 24
    color_type: hsv

esphome:
  name: WB5 LED Controller
  friendly_name: WB5 LED Controller

bk72xx:
  board: generic-bk7231n-qfn32-tuya


# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# serial connection to Tuya MCU
uart:
  rx_pin: RX1
  tx_pin: TX1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

# Enable Home Assistant API
api:
  encryption:
    key: "GET-A-KEY-HERE-https://esphome.io/components/api.html#configuration-variables"

ota:
  password: "CHANGE-THIS-PASSWORD-OR-REMOVE-OTA"

wifi: #if you dont have secrets setup change the values with your wifi name and password
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "WB5 LED Controller Fallback Hotspot"
    password: "CHANGE-THIS-PASSWORD-OR-DISABLE-AP-FALLBACK"

# Enable Web server
web_server:
  port: 80

captive_portal:

light:
  - platform: "tuya" # dont forget to set the correct mode whit the button on the controller
    name: "WB5 LED Controller"
    color_interlock: true # infinite loop isue when false (false is default)
    gamma_correct: 1 # has built in gamma correct wil cause issuses when changed
    default_transition_length: 0s # has built in transitions
    switch_datapoint: 20

    # for brightness
    dimmer_datapoint: 22
    min_value: 0
    max_value: 1000 # Max value is 1000 (default is 255)

    # for Correlated Color Temperature(CCT) or white channels
    color_temperature_datapoint: 23
    color_temperature_invert: true #set to true if connected as stated on the controller
    color_temperature_max_value: 1000 # Max value is 1000 (default is 255)
    cold_white_color_temperature: 6000 K # Change depending on LED strip
    warm_white_color_temperature: 2700 K # Change depending on LED strip

    # for RGB channels
    color_datapoint: 24
    color_type: hsv