esphome:
  name: dimmable_light

esp8266:
  board: esp8285

ota:
  safe_mode: True
  password: OTA_PASSWORD

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  use_address: X.X.X.X

mqtt:
  broker: X.X.X.X
  username: device_pub
  password: "MQTT_PASSWORD"

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

logger:
  baud_rate: 0

tuya:

light:
  - platform: "tuya"
    name: "dimmer"
    switch_datapoint: 20
    dimmer_datapoint: 22
    min_value: 1
    max_value: 1024