# Basic Config
esphome:
  name: "globe-34873"
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: "password"

output:
  - platform: esp8266_pwm
    id: ww
    pin: GPIO12
  - platform: esp8266_pwm
    id: cw
    pin: GPIO14

light:
- platform: cwww
  name: light
  cold_white: cw
  warm_white: ww
  cold_white_color_temperature: 5000 K
  warm_white_color_temperature: 2000 K
  restore_mode: RESTORE_DEFAULT_ON
  constant_brightness: true