#-------------------------------------------
substitutions:
  name: ttgo-t-display
  friendly_name: TTGO T-Display

esphome:
  name: "${name}"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ott:

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true

spi:
  clk_pin: GPIO17
  mosi_pin: GPIO16

display:
  - platform: st7789v
    model: "135x240"
    cs_pin: GPIO4
    dc_pin: GPIO5
    reset_pin: GPIO23
    backlight_pin: GPIO2
    rotation: 270
    update_interval: 1s
    lambda: |
      it.print(0, 0, id(font), "Hello World!");

font:
  - file: "fonts/Roboto-Regular.ttf"
    id: font
    size: 20

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: "${friendly_name} Button 1"
    id: button1

  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    name: "${friendly_name} Button 2"
    id: button2