substitutions:
  project_name: outdoor-Plug
  friendly_name: "Outdoor Plug"

esphome:
  name: ${project_name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true

bk72xx:
  board: generic-bk7231n-qfn32-tuya

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

# Enable logging
logger:
  level: DEBUG # Default

# Enable Home Assistant API
api:

ota:

# Note: UART config is optional
uart:
  rx_pin: P10 #RX1
  tx_pin: P11 #TX1
  baud_rate: 115200

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: P26
      inverted: true
    on_press:
      - switch.toggle: relay

light:
  - platform: status_led
    id: led_status
    pin:
      number: P17
      inverted: true

switch:
  - platform: gpio
    pin: P15
    id: relay
    name: ${friendly_name}
    on_turn_on:
      - light.turn_on: led_status
    on_turn_off:
      - light.turn_off: led_status