substitutions:
  device_name: "arlec_PC399HA_1"
  name: "ARLEC PC399HA 1"

esphome:
  name: ${device_name}
  comment: ${name}
  friendly_name: ${name}

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "api_password"

ota:
  password: "ota_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO3
      inverted: True
      mode: INPUT_PULLUP
    name: ${name} button
    filters:
      delayed_on_off: 100ms # Debouncing
    on_press:
      then:
        - switch.toggle: relay

switch:
  - platform: gpio
    pin: GPIO14
    name: "${name}"
    id: relay
    restore_mode: always on
    icon: mdi:power-socket-au
    on_turn_on:
      then:
        - output.turn_on: button_led
    on_turn_off:
      then:
        - output.turn_off: button_led

output:
  - platform: gpio
    id: button_led
    pin:
      number: GPIO13
      inverted: yes

sensor:
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    voltage_divider: 1650 # You may need to adjust this to be accurate
    current:
      name: "${name} Current"
      accuracy_decimals: 3
    voltage:
      name: "${name} Voltage"
      accuracy_decimals: 2
    power:
      name: "${name} Power"
      id: totalMediaWatts
    energy:
      name: "${name} Energy"
    update_interval: 10s