esphome:
  name: "Brilliant Smart RGBW"
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: <YOUR_SSID>
  password: <YOUR_WIFI_PASSPHRASE>

api:

logger:

ota:

sm16716:
  data_pin: GPIO4
  clock_pin: GPIO5
  num_channels: 3
  num_chips: 1

output:
  - platform: sm16716
    id: output_red
    channel: 2
    power_supply: rgb_power
  - platform: sm16716
    id: output_green
    channel: 1
    power_supply: rgb_power
  - platform: sm16716
    id: output_blue
    channel: 0
    power_supply: rgb_power
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO12

power_supply:
  - id: rgb_power
    pin: GPIO13

light:
  - platform: rgbw
    name: "brilliant_smart_rgbw"
    id: light_1
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    restore_mode: ALWAYS_ON