esphome:
  name: tuya-DY-CK400A-garage-door-opener

esp8266:
  board: esp_wroom_02

logger:

captive_portal:

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600

tuya:

binary_sensor:
  - platform: tuya
    id: contact
    sensor_datapoint: 101

switch:
  - platform: tuya
    id: mcu_cover
    switch_datapoint: 1

cover:
  - platform: template
    device_class: garage
    name: Garage Door
    lambda: 'return id(contact).state ? COVER_OPEN : COVER_CLOSED;'
    open_action:
      switch.turn_on: mcu_cover
    close_action:
      switch.turn_off: mcu_cover