substitutions:
  device_name: "living-room-light-1"
  friendly_name: "Living Room Light 1"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:
  - platform: uptime
    name: ${friendly_name} Uptime

  - platform: wifi_signal
    name: ${friendly_name} Signal Strength

output:
  - platform: esp8266_pwm
    pin: GPIO12
    inverted: true
    id: output_temperature
  - platform: esp8266_pwm
    pin: GPIO14
    id: output_brightness

light:
  - platform: color_temperature
    name: ${friendly_name}
    color_temperature: output_temperature
    brightness: output_brightness
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 3000 K