substitutions:
  device_name: brilliant-gu10
  device_id: brilliant_gu10_1
  friendly_name: "Brilliant GU10"
  device_description: Brilliant Smart CCT Globe GU10 (BL20887)
  device_ip: x.x.x.x
  gateway_ip: x.x.x.x
  subnet_mask: 255.255.255.0
  dns_ip: x.x.x.x

esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

logger:
api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

captive_portal:

output:
  - platform: esp8266_pwm
    id: ww_color_temp
    pin: GPIO12
  - platform: esp8266_pwm
    id: cw_color_temp
    pin: GPIO05

light:
  - platform: cwww
    name: ${friendly_name}
    id: ${device_id}
    cold_white: cw_color_temp
    warm_white: ww_color_temp
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    constant_brightness: true