esphome:
  name: mj-fc01-fan

esp8266:
  board: esp01_1m

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: <key>

ota:
  password: <password>

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "mj-fc01-fan Fallback Hotspot"
    password: <password>

captive_portal:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

tuya:

fan:
  - platform: "tuya"
    name: MJ FC01 Fan Speed
    switch_datapoint: 1
    speed_datapoint: 3
    speed_count: 4