# Basic Config

substitutions:
  device_name: led-strip
  device_description: RGB LED Strip Controller.
  friendly_name: LED Controller

esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap: #since we listed an SSID above, this AP mode will only enable if no WiFi connection could be made
    ssid: ${friendly_name}_AP
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Enable web server
web_server:
  port: 80

output:
  - platform: esp8266_pwm
    id: LED_controller
    pin: GPIO12

light:
  - platform: monochromatic
    name: "LED"
    output: LED_controller