# Basic Config
substitutions:
  device_name: "arlec_AEL10HA"
  name: "ARLEC AEL10HA"

esphome:
  name: ${device_name}
  comment: ${name}

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

logger:

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: "ota_password"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO01
      inverted: True
      mode: INPUT_PULLUP
    name: ${name}
    filters:
      delayed_on_off: 100ms
    on_press:
      then:
        - switch.toggle: relay

switch:
  - platform: gpio
    pin: GPIO14
    name: ${name}
    id: relay
    restore_mode: always off
    icon: mdi:power-socket-au
    on_turn_on:
      then:
        - output.turn_on: button_led
    on_turn_off:
      then:
        - output.turn_off: button_led

output:
  - platform: gpio
    id: button_led
    pin:
      number: GPIO13
      inverted: yes