# Variables
substitutions:
  number: "01"
  device_name: globe-light-${number}
  friendly_name: Globe Ceiling Light ${number}
  display_name: Globe Ceiling Light
  # Use recommended frequency - 1220Hz has bit_depth=16 and steps=65536
  ledc_frequency: "1200Hz"
  # Set transition time to 0s to eliminate lag
  transition_time: "0s"

# Basic Config
esphome:
  name: ${device_name}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

wifi:
  power_save_mode: none
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "ESPHome ${friendly_name}"
    password: !secret wifi_password_backup

logger:
  baud_rate: 115200

# Enable Home Assistant API
ota: {"password": !secret ota_password }
api:
  encryption:
    key: !secret encryption_key

# Enable NTP
time:
  - platform: sntp
    id: my_time

# General Config
text_sensor:
  - platform: version
    name: "${display_name} Version"
  - platform: wifi_info
    ip_address:
      name: "${display_name} IP Address"
    ssid:
      name: "${display_name} SSID"
    bssid:
      name: "${display_name} BSSID"

sensor:
  - platform: wifi_signal
    name: "${display_name} WiFi Signal"
    update_interval: 60s
    filters:
      - delta: 0.01
      - throttle: 300s
  - platform: uptime
    name: "${display_name} Uptime"
    filters:
      - throttle: 300s

switch:
  - platform: restart
    name: "${display_name} Restart"

# Light Config
light:
  - platform: rgbww
    name: "${friendly_name}"
    red: output_pwm1_red
    green: output_pwm2_green
    blue: output_pwm3_blue
    cold_white: output_pwm5_white_cold
    warm_white: output_pwm4_white_warm
    cold_white_color_temperature: 5000 K
    warm_white_color_temperature: 2000 K
    constant_brightness: true
    color_interlock: true
    default_transition_length: ${transition_time}
    restore_mode: RESTORE_AND_OFF

output:
  - platform: ledc
    pin: GPIO3
    frequency: ${ledc_frequency}
    id: output_pwm1_red
  - platform: ledc
    pin: GPIO10
    frequency: ${ledc_frequency}
    id: output_pwm2_green
  - platform: ledc
    pin: GPIO6
    frequency: ${ledc_frequency}
    id: output_pwm3_blue
  - platform: ledc
    pin: GPIO5
    frequency: ${ledc_frequency}
    id: output_pwm4_white_warm
  - platform: ledc
    pin: GPIO4
    frequency: ${ledc_frequency}
    id: output_pwm5_white_cold