uart:
  rx_pin: GPIOXX
  tx_pin: GPIOXX
  baud_rate: 4800

modbus:
  id: modbus1

modbus_controller:
  - id: wind_direction_meter
    address: 1
    modbus_id: modbus1
    setup_priority: -10
    command_throttle: 200ms
    update_interval: 60s

sensor:
  - platform: modbus_controller
    modbus_controller_id: wind_direction_meter
    name: "Wind direction gear"
    internal: true
    register_type: read
    address: 0
    value_type: U_WORD
    accuracy_decimals: 0
    on_value:
      - lambda: |-
          switch (int(x)) {
            case 0:
              id(wind_direction_cardinal).publish_state("N");  //North
              break;
            case 1:
              id(wind_direction_cardinal).publish_state("NE"); //North-East
              break;
            case 2:
              id(wind_direction_cardinal).publish_state("E");  //East
              break;
            case 3:
              id(wind_direction_cardinal).publish_state("SE"); //South-East
              break;
            case 4:
              id(wind_direction_cardinal).publish_state("S");  //South
              break;
            case 5:
              id(wind_direction_cardinal).publish_state("SW"); //South-West
              break;
            case 6:
              id(wind_direction_cardinal).publish_state("W");  //West
              break;
            case 7:
              id(wind_direction_cardinal).publish_state("NW"); //North-West
              break;
            default:
              id(wind_direction_cardinal).publish_state("");   //invalid
          }

  - platform: modbus_controller
    modbus_controller_id: wind_direction_meter
    name: "Wind direction degree"
    icon: mdi:compass-outline
    register_type: read
    address: 1
    value_type: U_WORD
    accuracy_decimals: 0
    state_class: measurement
    unit_of_measurement: "°"

text_sensor:
  - platform: template
    name: "Wind direction cardinal"
    id: wind_direction_cardinal
    icon: mdi:compass-rose

sensor:
  - platform: modbus_controller
    modbus_controller_id: wind_direction_meter
    name: "Device current address"
    register_type: read
    address: 2000
    value_type: U_WORD

number:
  - platform: modbus_controller
    modbus_controller_id: wind_direction_meter
    name: "Device new address"
    address: 2000
    register_type: holding
    value_type: U_WORD
    mode: box

sensor:
  - platform: modbus_controller
    modbus_controller_id: wind_direction_meter
    name: "Device current baud ID"
    register_type: read
    address: 2001
    value_type: U_WORD

number:
  - platform: modbus_controller
    modbus_controller_id: wind_direction_meter
    name: "Device new baud ID"
    address: 2001
    register_type: holding
    value_type: U_WORD
    mode: box