name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Convert AVIF to PNG
        run: |
          # Find all AVIF files and convert them to PNG
          find content -type f -name "*.avif" | while read file; do
            png_file="${file%.avif}.png"
            convert "$file" "$png_file"
            rm "$file"
            echo "Converted $file to $png_file"
          done

      - name: Install Pagefind
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: cloudcannon/pagefind

      - name: Build with Hugo
        run: hugo --minify

      - name: Build search index
        run: pagefind --site public

      - name: Deploy to Cloudflare Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=esphome-devices
