name: PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Convert AVIF to PNG
        run: |
          # Find all AVIF files and convert them to PNG
          find content -type f -name "*.avif" | while read file; do
            png_file="${file%.avif}.png"
            convert "$file" "$png_file"
            rm "$file"
            echo "Converted $file to $png_file"
          done

      - name: Install Pagefind
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with:
          repo: cloudcannon/pagefind

      - name: Build with Hugo
        run: hugo --minify

      - name: Build search index
        run: pagefind --site public

      - name: Deploy PR Preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name=esphome-devices --branch="pr-${{ github.event.pull_request.number }}"

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Preview deployment

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 Preview deployment is ready!
            
            You can view the preview at: https://pr-${{ github.event.pull_request.number }}.esphome-devices.pages.dev
            
            This preview will be automatically updated when you push new changes to this PR.
          edit-mode: replace
