uart:
  rx_pin: GPIOXX
  tx_pin: GPIOXX
  baud_rate: 4800

modbus:
  id: modbus1

modbus_controller:
  - id: wind_speed_meter
    address: 1
    modbus_id: modbus1
    setup_priority: -10
    command_throttle: 200ms
    update_interval: 1s

sensor:
  - platform: modbus_controller
    modbus_controller_id: wind_speed_meter
    name: "Wind speed"
    device_class: wind_speed
    register_type: read
    address: 0
    unit_of_measurement: "m/s"
    value_type: U_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
      - max:
          window_size: 5
          send_every: 5
      - exponential_moving_average:
          alpha: 0.1
          send_every: 12

sensor:
  - platform: modbus_controller
    modbus_controller_id: wind_speed_meter
    name: "Device current address"
    register_type: read
    address: 2000
    value_type: U_WORD

number:
  - platform: modbus_controller
    modbus_controller_id: wind_speed_meter
    name: "Device new address"
    address: 2000
    register_type: holding
    value_type: U_WORD
    mode: box

sensor:
  - platform: modbus_controller
    modbus_controller_id: wind_speed_meter
    name: "Device current baud ID"
    register_type: read
    address: 2001
    value_type: U_WORD

number:
  - platform: modbus_controller
    modbus_controller_id: wind_speed_meter
    name: "Device new baud ID"
    address: 2001
    register_type: holding
    value_type: U_WORD
    mode: box